action: train # train or test
name: classify_emg_lstm
modality: ["EMG"] # modality used
total_batch: 128 # total batch size if training is done with gradient accumulation
batch_size: 32 # batch size for the forward
gpus: null # gpus adopted
resume_from: null # checkpoint directory
models_dir: null # directory containing all the models

num_iter: 5000 # number of training iterations with total_batch size
lr_steps: 2000 # steps before reducing learning rate
eval_freq: 50 # evaluation frequency

dataset:
  annotations_path: action-net/data
  shift: D1-D1
  workers: 4
  features_name: save_actionNet
  RGB:
    data_path: null

models:
  RGB:
    model: RGB_Classifier
    kwargs: {}
    lr: 0.001
    sgd_momentum: 0.9
    weight_decay: 1e-7
  EMG:
    model: EMG_LSTM
    kwargs: {}
    lr: 0.001
    sgd_momentum: 0.9
    weight_decay: 1e-7


